steps:
# Dockerfileを利用してアプリのテストビルドとイメージのビルドを行う。$_VERSIONはトリガーの変数として設定します。
# $PROJECT_IDには使用中のプロジェクトIDが自動的に挿入されます
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile', '--tag=gcr.io/$PROJECT_ID/egawa-cluster:$_VERSION', '.']
# 作成したegawa-clusterイメージをPUSHする
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/egawa-cluster:$_VERSION"]
# aaaClusterを取得。$_ZONEはトリガーの変数として設定します。
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - beta
  - container
  - clusters
  - get-credentials
  - egawa-cluster
  - --zone=$_ZONE
  - --project=$PROJECT_ID
# アプリのデプロイ設定
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '--filename=deployment.yaml'
# NodePortのサービスを登録する 30580->8080
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '--filename=service.yaml'
# イメージをDeploymentにセットする。
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/egawa-cluster'
  - 'egawa-cluster=gcr.io/$PROJECT_ID/egawa-cluster:$_VERSION'
# デプロイのステータス確認
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'rollout'
  - 'status'
  - 'deployment/egawa-cluster'


