apiVersion: apps/v1
kind: Deployment
metadata:
 name: sample-server
spec:
 replicas: 2
 selector:
   matchLabels:
     name: sample-server
 template:
   metadata:
     labels:
       name: sample-server
   spec:
     containers:
     - name: sample-server
       image: gcr.io/study-sandbox/sample-server:latest
       ports:
       - containerPort: 8080
         protocol: TCP
 revisionHistoryLimit: 100
