apiVersion: apps/v1
kind: Deployment
metadata:
 name: egawa-cluster
spec:
 replicas: 2
 selector:
   matchLabels:
     name: egawa-cluster
 template:
   metadata:
     labels:
       name: egawa-cluster
   spec:
     containers:
     - name: egawa-cluster
       image: gcr.io/study-sandbox/egawa-cluster:latest
       ports:
       - containerPort: 8080
         protocol: TCP
 revisionHistoryLimit: 100
